name: Deploy NestJS to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # ✅ use the same version as your VPS

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: SSH and deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 18 || nvm install 18
            cd /root/NEST-CICD-PROJECT/nest-cicd-project
            git pull origin main
            npm install
            npm run build
            pm2 delete nestjs-app || true
            pm2 start dist/main.js --name nestjs-app
            pm2 save
          EOF
