name: Nest.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Stop current PM2 process by name
        run: pm2 stop nestjs-app || true

      - name: Start new PM2 process with name
        run: pm2 start dist/main.js --name nestjs-app

      - name: Save PM2 process list
        run: pm2 save